# core/constants.py

BTN_DL_YOUTUBE = "📺 دانلود از یوتیوب"
BTN_DL_INSTA = "📸 دانلود از اینستاگرام"
BTN_TRANSLATE = "🔤 ترجمه متن"
BTN_WEATHER = "🌤 آب و هوا"
BTN_BOOK = "📚 دانلود کتاب" 
BTN_YT_VIDEO = "🎥 دانلود ویدیو (تصویری)"
BTN_YT_AUDIO = "🎵 دانلود فایل صوتی (MP3)"
BTN_AI = "🤖 هوش مصنوعی"
BTN_AI_CHAT = "💬 دستیار هوشمند"
BTN_AI_OCR = "🖼 تبدیل عکس به متن (OCR)"
BTN_BACK = "🔙 بازگشت به منو"
BTN_AI_TTS = "🗣 تبدیل متن به صدا"
BTN_AI_IMAGE = "🎨 تولید عکس از متن"
BTN_MUSIC = "🎵 دانلود موسیقی"
BTN_MUSIC_SEARCH = "🔍 جستجوی آهنگ (نام/خواننده)"
BTN_MUSIC_SPOTIFY = "🎧 دانلود از اسپاتیفای (با لینک)"
